import type { Metadata } from 'next';
import Image from 'next/image';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image
          src="/logo.png"
          width={40}
          height={40}
          className="mx-auto"
          alt={'logo'}
        />
        <Link href="/">
          <h1 className="text-2xl text-white font-bold mt-4">Blog</h1>
        </Link>
        <p className="text-slate-300">🤟 Hello world. 💻</p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
        <h3>test</h3>
      </div>
    </footer>
  );

  return (
    <html lang="en">
      <body className="mx-auto max-w-4xl px-6">
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
